### PR TITLE
We no longer expect the puma command to be in bin dir in the project

### PR DESCRIPTION
**Pull request by oskarpearson**
`Warning - Untested with Unicorn`

If you use 'bundle exec puma', then the puma command is retrieved from the gem directory: it doesn't need to be included in the source tree.

### CODE REVIEW

**Comment by oskarpearson** [comment]
I've noticed there are other items I can remove here. I did the PR prematurely. Please hold.

**Comment by oskarpearson** [comment]
Hopefully ready to go now. Thanks.

**Comment by nickjj** [comment]
Were you having issues with this before the PR?

**Comment by oskarpearson** [comment]
Hi Nick

Thanks for taking the time to reply.

If you build a new project as per the simplest install guidelines at http://puma.io you can see that bin/puma\* aren't created:

eg:

```
vagrant@precise64:~$ rails new blog
...
vagrant@precise64:~$ cd blog
vagrant@precise64:~/blog$ echo 'gem "puma"' >> Gemfile
vagrant@precise64:~/blog$ bundle install
...
Using puma 2.9.0
...
vagrant@precise64:~/blog$ ls -al bin/puma*
ls: cannot access bin/puma*: No such file or directory
```

But, bundle exec puma still works:

```
vagrant@precise64:~/blog$ bundle exec puma
Puma starting in single mode...
* Version 2.9.0 (ruby 2.0.0-p353), codename: Team High Five
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
```

The problem is that the role includes a hardcoded reference to bin/puma - which isn't installed in the default config. When I used the role as-is, puma wouldn't start since the bin/puma command didn't exist. I suspect your test case may use an old method, which involved creating/copying the bin/puma files.

Hope that clarifies. Thanks again!

Oskar

**Comment by nickjj** [comment]
Ok, I see what you mean now. My test project was created using a tool that automatically made the binstubs. The hardcoding of bin/puma was redundant too because the initd script still uses bundle exec.

Thanks for the contribution.

**Pull request merged**
